version: '3'
services:
  postgres:
    image: postgres:10.6-alpine
    restart: 'no'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: prisma
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
